services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql1
    hostname: sql1
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Adm1234!
    ports:
      - "1433:1433"
    volumes:
      - ${DB_DATA_PATH}/sql:/var/opt/mssql/data
    restart: unless-stopped
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ${DB_DATA_PATH}/redis:/var/opt/mssql/data
    restart: unless-stopped

